"""
Session management for Kora Runtime.

Provides:
- SessionState: Pure data state (serializable, persistable)
- Session: User-facing session handle with execution capability
"""

from __future__ import annotations

import asyncio
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from kora.kernel.types import Message

if TYPE_CHECKING:
    from kora.kernel.model import Model
    from kora.kernel.tool import Tool
    from kora.runtime.agent import AgentConfig
    from kora.runtime.compressor import Compressor
    from kora.runtime.events import AnyEvent
    from kora.host.compression_policy import CompressionPolicy
    from kora.host.storage import Storage
    from kora.runtime.tool_policy import ToolSelectionPolicy, ToolResultProcessingPolicy
    from kora.runtime.termination import TerminationPolicy
    from kora.runtime.trace import TraceSink


@dataclass
class SessionUsage:
    """
    Session-level token usage statistics.

    Aggregated from provider-reported usage for session tracking.
    This is session telemetry, not compression policy by itself.
    """

    total_input_tokens: int = 0
    total_output_tokens: int = 0
    total_tokens: int = 0
    total_cached_input_tokens: int | None = None
    total_reasoning_tokens: int | None = None
    compression_count: int = 0
    last_compressed_at: datetime | None = None


@dataclass
class SummaryBlock:
    """
    A compressed summary of older conversation history.

    Summaries are generated by LLM and stored as system messages
    in the context reconstruction phase.
    """

    content: str
    message_range: tuple[int, int]  # Original message index range [start, end)
    created_at: datetime
    token_count: int


@dataclass
class SessionState:
    """
    Pure data state for a conversation session.

    This is the persistable representation of a session.
    Contains only data - no execution logic.
    """

    id: str
    agent_name: str
    messages: list[Message] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)

    # ADR-015: Context compression fields
    usage: SessionUsage = field(default_factory=SessionUsage)
    summary_blocks: list[SummaryBlock] = field(default_factory=list)
    archive_refs: list[str] = field(default_factory=list)

    @classmethod
    def create(cls, agent_name: str, *, session_id: str | None = None) -> SessionState:
        """Create a new session state."""
        return cls(
            id=session_id or str(uuid4()),
            agent_name=agent_name,
        )

    def add_message(self, message: Message) -> None:
        """Add a message to history."""
        self.messages.append(message)

    def add_user_message(self, content: str) -> None:
        """Add a user message."""
        self.messages.append(Message(role="user", content=content))

    def clear(self) -> None:
        """Clear message history."""
        self.messages.clear()

    def __len__(self) -> int:
        """Number of messages."""
        return len(self.messages)


class Session:
    """
    User-facing session handle with execution capability.

    Created via Agent.open_session(), this binds a SessionState
    with execution context (agent config and model).

    Example:
        ```python
        agent = Agent(name="assistant", tools=[...], model=model)
        session = agent.open_session()

        result = await session.send("Hello!")
        result = await session.send("Continue...")
        ```
    """

    def __init__(
        self,
        state: SessionState,
        agent: AgentConfig,
        model: Model | None = None,
        storage: Storage | None = None,
        compression_policy: CompressionPolicy | None = None,
        compressor: Compressor | None = None,
        tool_selection_policy: ToolSelectionPolicy | None = None,
        tool_result_processing_policy: ToolResultProcessingPolicy | None = None,
        termination_policy: TerminationPolicy | None = None,
        trace_sink: TraceSink | None = None,
    ) -> None:
        self._state = state
        self._agent = agent
        self._model = model
        self._storage = storage
        self._compression_policy = compression_policy
        self._compressor = compressor
        self._tool_selection_policy = tool_selection_policy
        self._tool_result_processing_policy = tool_result_processing_policy
        self._termination_policy = termination_policy
        self._trace_sink = trace_sink

    @property
    def id(self) -> str:
        """Session ID."""
        return self._state.id

    @property
    def state(self) -> SessionState:
        """The underlying session state."""
        return self._state

    @property
    def messages(self) -> list[Message]:
        """Message history."""
        return self._state.messages

    @property
    def system_prompt(self) -> str | None:
        """Get the current system prompt."""
        return self._agent.system_prompt

    @property
    def tools(self) -> list[Tool]:
        """Get the available tools."""
        return self._agent.tools

    @property
    def mode(self) -> str:
        """Get the current interaction mode."""
        return self._state.metadata.get("mode", "chat")

    @mode.setter
    def mode(self, value: str) -> None:
        """Set the interaction mode."""
        self._state.metadata["mode"] = value

    @property
    def model(self) -> Model | None:
        """Get the current model."""
        return self._model

    @property
    def tool_selection_policy(self) -> ToolSelectionPolicy | None:
        """Get the tool selection policy (ADR-023)."""
        return self._tool_selection_policy

    @property
    def tool_result_processing_policy(self) -> ToolResultProcessingPolicy | None:
        """Get the tool result processing policy (ADR-023)."""
        return self._tool_result_processing_policy

    @property
    def termination_policy(self) -> TerminationPolicy | None:
        """Get the termination policy (ADR-021)."""
        return self._termination_policy

    @property
    def trace_sink(self) -> TraceSink | None:
        """Get the trace sink (ADR-016)."""
        return self._trace_sink

    def set_model(self, model: Model) -> None:
        """Set the model for this session."""
        self._model = model

    def set_system_prompt(self, system_prompt: str | None) -> None:
        """
        Update the system prompt for future sends in this session.

        This is used by ContextRebuilder to re-render template variables
        after state changes like model switching.

        Args:
            system_prompt: The new system prompt text, or None to clear.
        """
        from dataclasses import replace
        self._agent = replace(self._agent, system_prompt=system_prompt)

    def save(self) -> None:
        """
        Persist session state to storage.

        Requires storage to be configured via Agent.
        """
        if self._storage is None:
            raise ValueError("No storage configured. Pass storage to Agent.")
        self._storage.save_session(self._state)

    @classmethod
    def load(
        cls,
        session_id: str,
        storage: Storage,
        agent: AgentConfig,
        model: Model | None = None,
        compression_policy: CompressionPolicy | None = None,
        compressor: Compressor | None = None,
        tool_selection_policy: ToolSelectionPolicy | None = None,
        tool_result_processing_policy: ToolResultProcessingPolicy | None = None,
        termination_policy: TerminationPolicy | None = None,
        trace_sink: TraceSink | None = None,
    ) -> Session | None:
        """
        Load a session from storage.

        Args:
            session_id: The session ID to load.
            storage: The storage backend.
            agent: The agent configuration.
            model: Optional model override.
            compression_policy: Optional compression policy (ADR-015).
            compressor: Optional compressor (ADR-015).
            tool_selection_policy: Optional tool selection policy (ADR-023).
            tool_result_processing_policy: Optional tool result processing policy (ADR-023).
            termination_policy: Optional termination policy (ADR-021).
            trace_sink: Optional trace sink (ADR-016).

        Returns:
            A Session instance, or None if not found.
        """
        state = storage.load_session(session_id)
        if state is None:
            return None
        return cls(
            state=state,
            agent=agent,
            model=model,
            storage=storage,
            compression_policy=compression_policy,
            compressor=compressor,
            tool_selection_policy=tool_selection_policy,
            tool_result_processing_policy=tool_result_processing_policy,
            termination_policy=termination_policy,
            trace_sink=trace_sink,
        )

    async def send(
        self,
        message: str,
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: Callable[[list[str]], str | None] | None = None,
    ) -> str:
        """
        Send a message in this session.

        Args:
            message: The user message.
            model: Optional model override.
            on_event: Optional callback for events.
            skill_activation_handler: Optional handler for skill activation (ADR-027).

        Returns:
            The agent's response text.

        Raises:
            ValueError: If no model is configured.
        """
        from kora.runtime import Run, RunCompleted

        active_model = model or self._model
        if active_model is None:
            raise ValueError("No model configured. Pass model to Agent, Session, or send().")

        run = Run.create(
            self._agent,
            self._state,
            active_model,
            storage=self._storage,
            trace_sink=self._trace_sink,
            termination_policy=self._termination_policy,
            tool_selection_policy=self._tool_selection_policy,
            tool_result_processing_policy=self._tool_result_processing_policy,
        )

        # ADR-015: Inject compression components
        run.compression_policy = self._compression_policy
        run.compressor = self._compressor

        # ADR-027: Inject skill activation handler
        run.skill_activation_handler = skill_activation_handler

        if on_event:
            run.on_event(on_event)

        final_content: str | None = None
        async for event in run.execute(message):
            if isinstance(event, RunCompleted):
                final_content = event.final_content

        return final_content or ""

    async def send_collecting(
        self,
        message: str,
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: Callable[[list[str]], str | None] | None = None,
    ) -> tuple[str, list[AnyEvent]]:
        """
        Send a message and collect the emitted runtime events.

        This is useful for Host-managed multi-phase flows where the caller
        needs to inspect a phase before deciding whether to reveal it,
        roll it back, or continue with a follow-up phase.
        """
        events: list[AnyEvent] = []

        def collect(event: AnyEvent) -> None:
            events.append(event)
            if on_event is not None:
                on_event(event)

        final_content = await self.send(
            message, model=model, on_event=collect, skill_activation_handler=skill_activation_handler
        )
        return final_content, events

    def send_sync(
        self,
        message: str,
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: Callable[[list[str]], str | None] | None = None,
    ) -> str:
        """Synchronous send."""
        return asyncio.run(
            self.send(message, model=model, on_event=on_event, skill_activation_handler=skill_activation_handler)
        )

    def send_collecting_sync(
        self,
        message: str,
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: Callable[[list[str]], str | None] | None = None,
    ) -> tuple[str, list[AnyEvent]]:
        """Synchronous variant of send_collecting()."""
        return asyncio.run(
            self.send_collecting(message, model=model, on_event=on_event, skill_activation_handler=skill_activation_handler)
        )

    def checkpoint(self) -> int:
        """
        Return a durable turn checkpoint for later rollback.

        The checkpoint is the current message count in session history.
        """
        return len(self._state.messages)

    def rollback_to(self, checkpoint: int) -> None:
        """
        Discard session history written after a checkpoint.

        This supports hidden follow-up phases where intermediate runs should
        not remain in the persisted conversation state.
        """
        del self._state.messages[checkpoint:]

    def clear(self) -> None:
        """Clear message history."""
        self._state.clear()

    def __len__(self) -> int:
        """Number of messages."""
        return len(self._state)

    def __repr__(self) -> str:
        return f"Session(id={self.id[:8]}..., messages={len(self)})"
