import { useQuery } from '@tanstack/react-query'
import { api } from '../api'
import { ErrorBanner } from '../components/Modal'

export default function SettingsPage() {
  const system = useQuery({ queryKey: ['system'], queryFn: () => api.get('/api/system').then((r) => r.data) })
  const providers = useQuery({ queryKey: ['providers'], queryFn: () => api.get('/api/models/providers').then((r) => r.data) })
  return <div className="p-8"><div className="mb-6"><h2 className="text-2xl font-bold dark:text-white">Settings & runtime</h2><p className="text-gray-500">Read-only operational context. Credentials remain in environment variables.</p></div><ErrorBanner error={system.error || providers.error} /><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-white p-6 dark:bg-gray-800"><h3 className="font-semibold dark:text-white">Gateway runtime</h3><dl className="mt-4 space-y-3 text-sm">{system.data && Object.entries(system.data).map(([key, value]) => <div key={key}><dt className="text-gray-500">{key.replace(/_/g, ' ')}</dt><dd className="break-all font-mono dark:text-white">{String(value)}</dd></div>)}</dl></section><section className="rounded-xl border bg-white p-6 dark:bg-gray-800"><h3 className="font-semibold dark:text-white">Model providers</h3><div className="mt-4 space-y-3">{providers.data?.map((provider: any) => <div key={provider.id} className="rounded-lg bg-gray-50 p-3 dark:bg-gray-900"><div className="flex items-center justify-between gap-3"><strong className="dark:text-white">{provider.name}</strong><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-xs ${provider.configured === true ? 'bg-green-100 text-green-700' : provider.configured === false ? 'bg-amber-100 text-amber-700' : 'bg-gray-200 text-gray-600'}`}>{provider.configured === true ? 'Configured' : provider.configured === false ? 'Credential missing' : 'Custom auth'}</span><span className="text-xs text-gray-500">{provider.model_count} models</span></div></div><p className="mt-1 truncate font-mono text-xs text-gray-500">{provider.base_url}</p><p className="mt-1 text-xs text-gray-400">Credential: {provider.credential_env || 'not required / custom'}</p></div>)}</div></section></div></div>
}
