"""
Session management for Quenda Runtime.

Provides:
- SessionState: Pure data state (serializable, persistable)
- Session: User-facing session handle with execution capability
"""

from __future__ import annotations

import asyncio
import threading
from collections.abc import Callable, Coroutine, Sequence
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Any, TypeVar
from uuid import uuid4

from quenda.kernel.types import ImageContent, ImageRef, Message, TextContent
from quenda.runtime.cancellation import CancellationToken

if TYPE_CHECKING:
    from quenda.kernel.model import Model
    from quenda.kernel.tool import Tool
    from quenda.runtime.agent import AgentConfig
    from quenda.runtime.compressor import Compressor
    from quenda.runtime.events import AnyEvent
    from quenda.runtime.ports.after_run import AfterRunHandler
    from quenda.runtime.ports.compression import CompressionPolicy
    from quenda.runtime.ports.storage import Storage
    from quenda.runtime.run import SkillActivationHandler
    from quenda.runtime.termination import TerminationPolicy
    from quenda.runtime.tool_policy import ToolResultProcessingPolicy, ToolSelectionPolicy
    from quenda.runtime.trace import TraceSink


_T = TypeVar("_T")


@dataclass
class SessionUsage:
    """
    Session-level token usage statistics.

    Aggregated from provider-reported usage for session tracking.
    This is session telemetry, not compression policy by itself.
    """

    total_input_tokens: int = 0
    total_output_tokens: int = 0
    total_tokens: int = 0
    total_cached_input_tokens: int | None = None
    total_cache_creation_input_tokens: int | None = None
    total_reasoning_tokens: int | None = None
    compression_count: int = 0
    last_compressed_at: datetime | None = None


@dataclass
class SummaryBlock:
    """
    A compressed summary of older conversation history.

    Summaries are generated by LLM and stored as system messages
    in the context reconstruction phase.
    """

    content: str
    message_range: tuple[int, int]  # Original message index range [start, end)
    created_at: datetime
    token_count: int


@dataclass
class SessionState:
    """
    Pure data state for a conversation session.

    This is the persistable representation of a session.
    Contains only data - no execution logic.
    """

    id: str
    agent_name: str
    messages: list[Message] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)

    # ADR-015: Context compression fields
    usage: SessionUsage = field(default_factory=SessionUsage)
    summary_blocks: list[SummaryBlock] = field(default_factory=list)
    archive_refs: list[str] = field(default_factory=list)

    # ADR-027: Image references (multimodal support)
    image_refs: dict[str, ImageRef] = field(default_factory=dict)

    @classmethod
    def create(cls, agent_name: str, *, session_id: str | None = None) -> SessionState:
        """Create a new session state."""
        return cls(
            id=session_id or str(uuid4()),
            agent_name=agent_name,
        )

    def add_message(self, message: Message) -> None:
        """Add a message to history."""
        self.messages.append(message)

    def add_user_message(self, content: str | Sequence[TextContent | ImageContent]) -> None:
        """Add a user message (text or multimodal)."""
        if isinstance(content, str):
            self.messages.append(Message(role="user", content=content))
        else:
            self.messages.append(Message(role="user", content=content))

    def add_image_ref(self, ref: ImageRef) -> None:
        """Add an image reference to the session."""
        self.image_refs[ref.id] = ref

    def get_image_ref(self, ref_id: str) -> ImageRef | None:
        """Get an image reference by ID."""
        return self.image_refs.get(ref_id)

    def clear(self) -> None:
        """Clear message history."""
        self.messages.clear()

    def __len__(self) -> int:
        """Number of messages."""
        return len(self.messages)


class Session:
    """
    User-facing session handle with execution capability.

    Created via Agent.open_session(), this binds a SessionState
    with execution context (agent config and model).

    ADR-028: Supports capability-based model routing with vision_model.

    Example:
        ```python
        agent = Agent(name="assistant", tools=[...], model=model)
        session = agent.open_session()

        result = await session.send("Hello!")
        result = await session.send("Continue...")
        ```
    """

    def __init__(
        self,
        state: SessionState,
        agent: AgentConfig,
        model: Model | None = None,
        storage: Storage | None = None,
        compression_policy: CompressionPolicy | None = None,
        compressor: Compressor | None = None,
        tool_selection_policy: ToolSelectionPolicy | None = None,
        tool_result_processing_policy: ToolResultProcessingPolicy | None = None,
        termination_policy: TerminationPolicy | None = None,
        trace_sink: TraceSink | None = None,
        vision_model: Model | None = None,
        capability_routing: bool = True,
        microcompact_trigger_tokens: int = 50_000,
        microcompact_keep_last_tool_results: int = 8,
        after_run_handler: AfterRunHandler | None = None,
    ) -> None:
        self._state = state
        self._agent = agent
        self._model = model
        self._storage = storage
        self._compression_policy = compression_policy
        self._compressor = compressor
        self._tool_selection_policy = tool_selection_policy
        self._tool_result_processing_policy = tool_result_processing_policy
        self._termination_policy = termination_policy
        self._trace_sink = trace_sink
        self._vision_model = vision_model
        self._capability_routing = capability_routing
        self._microcompact_trigger_tokens = microcompact_trigger_tokens
        self._microcompact_keep_last_tool_results = microcompact_keep_last_tool_results
        self._after_run_handler = after_run_handler
        # Persistent event loop for MCP connections
        self._loop: asyncio.AbstractEventLoop | None = None
        self._send_lock = threading.Lock()

    @property
    def id(self) -> str:
        """Session ID."""
        return self._state.id

    @property
    def state(self) -> SessionState:
        """The underlying session state."""
        return self._state

    @property
    def messages(self) -> list[Message]:
        """Message history."""
        return self._state.messages

    @property
    def system_prompt(self) -> str | None:
        """Get the current system prompt."""
        return self._agent.system_prompt

    @property
    def tools(self) -> list[Tool]:
        """Get the available tools."""
        return self._agent.tools

    @property
    def mode(self) -> str:
        """Get the current interaction mode."""
        value = self._state.metadata.get("mode", "chat")
        return value if isinstance(value, str) else "chat"

    @mode.setter
    def mode(self, value: str) -> None:
        """Set the interaction mode."""
        self._state.metadata["mode"] = value

    @property
    def model(self) -> Model | None:
        """Get the current model."""
        return self._model

    @property
    def tool_selection_policy(self) -> ToolSelectionPolicy | None:
        """Get the tool selection policy (ADR-023)."""
        return self._tool_selection_policy

    @property
    def tool_result_processing_policy(self) -> ToolResultProcessingPolicy | None:
        """Get the tool result processing policy (ADR-023)."""
        return self._tool_result_processing_policy

    @property
    def termination_policy(self) -> TerminationPolicy | None:
        """Get the termination policy (ADR-021)."""
        return self._termination_policy

    @property
    def trace_sink(self) -> TraceSink | None:
        """Get the trace sink (ADR-016)."""
        return self._trace_sink

    def set_model(self, model: Model) -> None:
        """Set the model for this session."""
        self._model = model

    def set_system_prompt(self, system_prompt: str | None) -> None:
        """
        Update the system prompt for future sends in this session.

        This is used by ContextRebuilder to re-render template variables
        after state changes like model switching.

        Args:
            system_prompt: The new system prompt text, or None to clear.
        """
        from dataclasses import replace
        self._agent = replace(self._agent, system_prompt=system_prompt)

    def save(self) -> None:
        """
        Persist session state to storage.

        Requires storage to be configured via Agent.
        """
        if self._storage is None:
            raise ValueError("No storage configured. Pass storage to Agent.")
        self._storage.save_session(self._state)

    @classmethod
    def load(
        cls,
        session_id: str,
        storage: Storage,
        agent: AgentConfig,
        model: Model | None = None,
        compression_policy: CompressionPolicy | None = None,
        compressor: Compressor | None = None,
        tool_selection_policy: ToolSelectionPolicy | None = None,
        tool_result_processing_policy: ToolResultProcessingPolicy | None = None,
        termination_policy: TerminationPolicy | None = None,
        trace_sink: TraceSink | None = None,
        microcompact_trigger_tokens: int = 50_000,
        microcompact_keep_last_tool_results: int = 8,
        after_run_handler: AfterRunHandler | None = None,
    ) -> Session | None:
        """
        Load a session from storage.

        Args:
            session_id: The session ID to load.
            storage: The storage backend.
            agent: The agent configuration.
            model: Optional model override.
            compression_policy: Optional compression policy (ADR-015).
            compressor: Optional compressor (ADR-015).
            tool_selection_policy: Optional tool selection policy (ADR-023).
            tool_result_processing_policy: Optional tool result processing policy (ADR-023).
            termination_policy: Optional termination policy (ADR-021).
            trace_sink: Optional trace sink (ADR-016).

        Returns:
            A Session instance, or None if not found.
        """
        state = storage.load_session(session_id)
        if state is None:
            return None
        return cls(
            state=state,
            agent=agent,
            model=model,
            storage=storage,
            compression_policy=compression_policy,
            compressor=compressor,
            tool_selection_policy=tool_selection_policy,
            tool_result_processing_policy=tool_result_processing_policy,
            termination_policy=termination_policy,
            trace_sink=trace_sink,
            microcompact_trigger_tokens=microcompact_trigger_tokens,
            microcompact_keep_last_tool_results=microcompact_keep_last_tool_results,
            after_run_handler=after_run_handler,
        )

    async def send(
        self,
        message: str | Sequence[TextContent | ImageContent],
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: SkillActivationHandler | None = None,
        cancellation_token: CancellationToken | None = None,
    ) -> str:
        """
        Send a message in this session.

        Args:
            message: The user message (text or multimodal content).
            model: Optional model override.
            on_event: Optional callback for events.
            skill_activation_handler: Optional handler for skill activation (ADR-027).
            cancellation_token: Optional cancellation state for this Run only.

        Returns:
            The agent's response text.

        Raises:
            ValueError: If no model is configured.
            RuntimeError: If another Run is already writing this Session.
        """
        if not self._send_lock.acquire(blocking=False):
            raise RuntimeError(f"Session {self.id} already has an active Run")

        try:
            from quenda.runtime import Run, RunCompleted

            active_model = model or self._model
            if active_model is None:
                raise ValueError("No model configured. Pass model to Agent, Session, or send().")

            run = Run.create(
                self._agent,
                self._state,
                active_model,
                storage=self._storage,
                trace_sink=self._trace_sink,
                termination_policy=self._termination_policy,
                tool_selection_policy=self._tool_selection_policy,
                tool_result_processing_policy=self._tool_result_processing_policy,
                vision_model=self._vision_model,
                capability_routing=self._capability_routing,
                microcompact_trigger_tokens=self._microcompact_trigger_tokens,
                microcompact_keep_last_tool_results=self._microcompact_keep_last_tool_results,
                cancellation_token=cancellation_token,
            )

            # ADR-015: Inject compression components
            run.compression_policy = self._compression_policy
            run.compressor = self._compressor

            # ADR-027: Inject skill activation handler
            run.skill_activation_handler = skill_activation_handler

            if on_event:
                run.on_event(on_event)

            final_content: str | None = None
            completed_event: RunCompleted | None = None
            async for event in run.execute(message):
                if isinstance(event, RunCompleted):
                    final_content = event.final_content

                    completed_event = event

            if completed_event is not None and self._after_run_handler is not None:
                from quenda.runtime.events import EvolutionFailed
                from quenda.runtime.ports.after_run import AfterRunContext

                try:
                    maintenance_events = await self._after_run_handler.process(
                        AfterRunContext(
                            session_id=self._state.id,
                            agent_name=self._state.agent_name,
                            messages=tuple(self._state.messages),
                            completed=completed_event,
                        )
                    )
                except Exception as exc:
                    maintenance_events = [
                        EvolutionFailed(
                            run_id=completed_event.run_id,
                            error_type=type(exc).__name__,
                            error_message=str(exc),
                        )
                    ]
                for maintenance_event in maintenance_events:
                    if not maintenance_event.run_id:
                        object.__setattr__(
                            maintenance_event,
                            "run_id",
                            completed_event.run_id,
                        )
                    if on_event is not None:
                        try:
                            on_event(maintenance_event)
                        except Exception:
                            pass
                    if self._trace_sink is not None:
                        try:
                            self._trace_sink.record(maintenance_event)
                        except Exception:
                            pass

            return final_content or ""
        finally:
            self._send_lock.release()

    async def send_collecting(
        self,
        message: str | Sequence[TextContent | ImageContent],
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: SkillActivationHandler | None = None,
        cancellation_token: CancellationToken | None = None,
    ) -> tuple[str, list[AnyEvent]]:
        """
        Send a message and collect the emitted runtime events.

        This is useful for Host-managed multi-phase flows where the caller
        needs to inspect a phase before deciding whether to reveal it,
        roll it back, or continue with a follow-up phase.
        """
        events: list[AnyEvent] = []

        def collect(event: AnyEvent) -> None:
            events.append(event)
            if on_event is not None:
                on_event(event)

        final_content = await self.send(
            message, model=model, on_event=collect,
            skill_activation_handler=skill_activation_handler,
            cancellation_token=cancellation_token,
        )
        return final_content, events

    def _get_or_create_loop(self) -> asyncio.AbstractEventLoop:
        """Get or create a persistent event loop."""
        if self._loop is None or self._loop.is_closed():
            self._loop = asyncio.new_event_loop()
        return self._loop

    def _run_sync(
        self,
        awaitable: Coroutine[Any, Any, _T],
        *,
        cancellation_token: CancellationToken | None = None,
    ) -> _T:
        """Run an awaitable and ensure Ctrl+C cannot leave a task pending."""
        loop = self._get_or_create_loop()
        task = loop.create_task(awaitable)
        try:
            return loop.run_until_complete(task)
        except KeyboardInterrupt:
            if cancellation_token is not None:
                cancellation_token.cancel()
            # run_until_complete stops the loop but does not cancel its task.
            # Drain the cancellation so a later send cannot resume the old run.
            task.cancel()
            try:
                loop.run_until_complete(task)
            except asyncio.CancelledError:
                pass
            raise

    def send_sync(
        self,
        message: str | Sequence[TextContent | ImageContent],
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: SkillActivationHandler | None = None,
    ) -> str:
        """Synchronous send using persistent event loop."""
        cancellation_token = CancellationToken()
        return self._run_sync(
            self.send(
                message, model=model, on_event=on_event,
                skill_activation_handler=skill_activation_handler,
                cancellation_token=cancellation_token,
            ),
            cancellation_token=cancellation_token,
        )

    def send_collecting_sync(
        self,
        message: str | Sequence[TextContent | ImageContent],
        *,
        model: Model | None = None,
        on_event: Callable[[AnyEvent], None] | None = None,
        skill_activation_handler: SkillActivationHandler | None = None,
    ) -> tuple[str, list[AnyEvent]]:
        """Synchronous variant of send_collecting() using persistent event loop."""
        cancellation_token = CancellationToken()
        return self._run_sync(
            self.send_collecting(
                message, model=model, on_event=on_event,
                skill_activation_handler=skill_activation_handler,
                cancellation_token=cancellation_token,
            ),
            cancellation_token=cancellation_token,
        )

    def close(self) -> None:
        """Close the session and clean up resources."""
        if self._loop is not None and not self._loop.is_closed():
            self._loop.close()
            self._loop = None

    def checkpoint(self) -> int:
        """
        Return a durable turn checkpoint for later rollback.

        The checkpoint is the current message count in session history.
        """
        return len(self._state.messages)

    def rollback_to(self, checkpoint: int) -> None:
        """
        Discard session history written after a checkpoint.

        This supports hidden follow-up phases where intermediate runs should
        not remain in the persisted conversation state.
        """
        del self._state.messages[checkpoint:]

    def clear(self) -> None:
        """Clear message history."""
        self._state.clear()

    def __len__(self) -> int:
        """Number of messages."""
        return len(self._state)

    def __repr__(self) -> str:
        return f"Session(id={self.id[:8]}..., messages={len(self)})"
